name: AtlasMasaIOS
options:
  bundleIdPrefix: com.atlasmasa
settings:
  base:
    SWIFT_VERSION: 5.10
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
packages: {}
targets:
  AtlasMasaIOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AtlasMasaIOS/Sources
    info:
      path: AtlasMasaIOS/Info.plist
      properties:
        CFBundleDisplayName: Atlas/אטלס
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSFaceIDUsageDescription: Use Face ID to authenticate passkeys and protect your Atlas/אטלס account.
        ITSAppUsesNonExemptEncryption: false
    entitlements:
      path: AtlasMasaIOS/AtlasMasaIOS.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.atlasmasa.ios
        DEVELOPMENT_TEAM: BW93SGS88H
  AtlasMasaIOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AtlasMasaIOS/Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.atlasmasa.ios.tests
    dependencies:
      - target: AtlasMasaIOS
